services:
  app:
   # build:
   #   context: .
    #  dockerfile: Dockerfile
    image: tenants-manager:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tenants-manager
      # Add your Clerk environment variables here
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_bW92ZWQtbmFyd2hhbC0zMS5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_rFuwQXDXl9dAZxPzFIUuABgtsCYxdYJWNYwaGL329B
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local 